### PR TITLE
5.0.0 - Remove NODE_ENV, allow output overrides, external build configs

### PR DESCRIPTION
**Pull request by peripateticus**
Summary of changes:

- Remove NODE_ENV from the API. We rely totally on the build commands now, i.e., `febs dev`, `febs prod`.
- Refactor the build configs out to external repository.  This is in preparation for future work around build profiles.
- Updates to Readme around different ways of setting output path.
- Remove extraneous unit tests.
- Running just `febs` will display help.
- Fix code coverage.

### CODE REVIEW

**Comment by dewilli-rei** [comment]
https://github.com/rei/febs/pull/95

**Comment by peripateticus** [comment]
A couple more updates coming...

**Comment by peripateticus** [comment]
OK, I think this ready for final review!

**Comment by dewilli-rei** [comment]
```
         /|\
       /__| )
     /____| ))
   /______| )))
 /________|  )))
         _|____))
 \======| o o /
~~~~~~~~~~~~~~~~~~~, Good stuff - Ship it!

**Comment by peripateticus** [comment]
Planning on merging this today, let me know if anyone needs more review time.

**Pull request merged**
